require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  CacheRootDirectory: "tmp/rubocop_cache"
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - "db/*"
    - "vendor/bundle/**/*"

inherit_from:
  - .rubocop/custom.yml
